#!/usr/bin/env bash

set
pwd
ls -la
echo $DOCKERFILE_PATH

TYPO3_MAJOR_VERSION=9

# Build with default args in Dockerfile
docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME .
docker build --build-arg TARGET_SERVICE=web -f $DOCKERFILE_PATH -t $DOCKER_REPO:web-$TYPO3_MAJOR_VERSION .
docker build --build-arg TARGET_SERVICE=php --build-arg TARGET_ENVIRONMENT=development -f $DOCKERFILE_PATH -t $DOCKER_REPO:typo3-$TYPO3_MAJOR_VERSION-dev .
docker build --build-arg TARGET_SERVICE=web --build-arg TARGET_ENVIRONMENT=development -f $DOCKERFILE_PATH -t $DOCKER_REPO:web-$TYPO3_MAJOR_VERSION-dev .