#!/usr/bin/env bash

TYPO3_MAJOR_VERSION=11

pushd ../

# Build with default args in Dockerfile
docker build --target web-development --build-arg TARGET_ENVIRONMENT=development -f $DOCKERFILE_PATH -t $DOCKER_REPO:web-$TYPO3_MAJOR_VERSION-dev .
docker build --target php-development --build-arg TARGET_ENVIRONMENT=development -f $DOCKERFILE_PATH -t $DOCKER_REPO:typo3-$TYPO3_MAJOR_VERSION-dev .

docker build --target web-production -f $DOCKERFILE_PATH -t $DOCKER_REPO:web-$TYPO3_MAJOR_VERSION .
docker build --target php-production -f $DOCKERFILE_PATH -t $IMAGE_NAME .

popd