FROM composer:latest AS composer

COPY typo3 /app

RUN composer install --no-ansi --no-interaction --no-progress --classmap-authoritative

FROM nginx:alpine

COPY --chown=82 --from=composer /app /app

COPY web/typo3.conf /etc/nginx/
COPY web/default.conf.template /etc/nginx/conf.d/

ENV VHOST web.typo3

CMD ["sh", "-c", "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]

WORKDIR /app
