version: '3.5'
services:
  web:
    build:
      dockerfile: .docker/Dockerfile.dev
      args:
        TARGET_SERVICE: web

  typo3:
    build:
      dockerfile: .docker/Dockerfile.dev
      args:
        TARGET_SERVICE: php

