version: "3.8"
services:
  web:
    build:
      dockerfile: .docker/Dockerfile
      target: web-development
      args:
        TARGET_ENVIRONMENT: development

  typo3:
    build:
      dockerfile: .docker/Dockerfile
      target: php-development
      args:
        TARGET_ENVIRONMENT: development
