version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile.Web

  typo3:
    build:
      context: .
      dockerfile: .docker/Dockerfile.TYPO3
      args:
        REDIS: ${REDIS}
        LDAP: ${LDAP}
