version: '3.5'
services:
  web:
    build:
      dockerfile: .docker/Dockerfile
      args:
        TARGET_ENVIRONMENT: development
        TARGET_SERVICE: web

  typo3:
    build:
      dockerfile: .docker/Dockerfile
      args:
        TARGET_ENVIRONMENT: development
        TARGET_SERVICE: php

