version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: web-production
      args:
        TARGET_ENVIRONMENT: production

  typo3:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: php-production
      args:
        TARGET_ENVIRONMENT: production
