version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        TARGET_ENVIRONMENT: production
        TARGET_SERVICE: web

  typo3:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        TARGET_ENVIRONMENT: production
        TARGET_SERVICE: php