FROM t3easy/php-dev:7.2

COPY .docker/ca-certificates /usr/local/share/ca-certificates
RUN update-ca-certificates

ARG LDAP=1
ARG REDIS=1
ARG REDIS_VERSION=4.3.0

RUN set -ex; \
    \
    apk add --no-cache --virtual .build-deps \
        $PHPIZE_DEPS \
        openldap-dev \
    ; \
    if [ "$LDAP" = "1" ]; then \
        docker-php-ext-configure ldap; \
        docker-php-ext-install ldap; \
    fi; \
    \
    if [ "$REDIS" = "1" ]; then \
        pecl install redis-$REDIS_VERSION; \
        docker-php-ext-enable redis; \
        rm -rf /tmp/pear; \
    fi; \
    \
    runDeps="$( \
        scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
            | tr ',' '\n' \
            | sort -u \
            | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
    )"; \
    apk add --virtual .typo3-phpext-rundeps $runDeps; \
    apk del .build-deps

ENV PATH "/app/vendor/bin:$PATH"
ENV TYPO3_CONTEXT Development
