ARG PHP_VERSION=7.2
FROM t3easy/php:${PHP_VERSION}-development AS runtime

COPY .docker/cron.sh /usr/local/bin/cron
RUN rm /var/spool/cron/crontabs/root \
 && echo '*/15 * * * * php -f /app/vendor/bin/typo3 scheduler:run' > /var/spool/cron/crontabs/www-data

COPY .docker/ca-certificates /usr/local/share/ca-certificates
RUN update-ca-certificates

ENV PATH "/app/vendor/bin:$PATH"
ENV TYPO3_CONTEXT Development