FROM nginx:alpine

COPY .docker/web/typo3.conf /etc/nginx/
COPY .docker/web/default.conf.template /etc/nginx/conf.d/

ENV VHOST typo3.localhost

CMD ["sh", "-c", "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]

WORKDIR /app
