FROM t3easy/php-dev:7.2

COPY .docker/ca-certificates /usr/local/share/ca-certificates
RUN update-ca-certificates

# Install PHP LDAP extension
ARG LDAP=1
RUN if [ "$LDAP" = "1" ]; then \
        apk add --no-cache libldap && \
        apk add --no-cache --virtual .build-deps \
            openldap-dev && \
        docker-php-ext-install ldap && \
        apk del .build-deps; \
    fi

# Install PHP Redis extension
ARG REDIS=1
RUN if [ "$REDIS" = "1" ]; then \
        apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS && \
        pecl install redis && \
        docker-php-ext-enable redis && \
        apk del .phpize-deps && \
        rm -rf /tmp/pear; \
    fi

ENV PATH "/app/vendor/bin:$PATH"
ENV TYPO3_CONTEXT Development
