FROM composer:latest AS composer

COPY . /app

# Remove .docker because it cannot be excluded with .dockerignore
RUN rm -rf /app/.docker

RUN composer install --no-ansi --no-interaction --no-dev --no-progress --classmap-authoritative --ignore-platform-reqs

FROM nginx:alpine

COPY --chown=82 --from=composer /app /app

COPY .docker/web/typo3.conf /etc/nginx/
COPY .docker/web/default.conf /etc/nginx/conf.d/

WORKDIR /app
