services:
  typo3:
    depends_on:
    - db
    networks:
      typo3-db:
    env_file:
    - .docker/.env.db
    environment:
      MYSQL_HOST: db

  db:
    image: ${DB_IMAGE}
    networks:
      typo3-db:
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD:
    env_file:
    - .docker/.env.db
    restart: "${RESTART}"

networks:
  typo3-db:
