version: "3.8"
services:
  scheduler:
    image: ${TYPO3_IMAGE}
    entrypoint: cron
    depends_on:
    - db
    #- redis
    #- solr
    networks:
      typo3-db:
      #typo3-redis:
      #typo3-solr:
    env_file:
    - .docker/.env.db
    environment:
      MYSQL_HOST: db
    restart: ${RESTART}